export const EQUIPMENT_LOADING = 'EQUIPMENT_LOADING';
export const EQUIPMENT_FAILED = 'EQUIPMENT_FAILED';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const SELECT_EQUIPMENT = 'SELECT_EQUIPMENT'

export const PARTS_LOADING = 'PARTS_LOADING';
export const PARTS_FAILED = 'PARTS_FAILED';
export const ADD_PARTS = 'ADD_PARTS';